### ISSUE TITLE
UpgradeAgent Contract issue

### ISSUE THREAD

**Issue by ghost** [TokenMarketNet/ico#140]
Hello,

Is anyone able to please share how they were able to sucessfully run upgrade for a token ?

This is the token contract
https://ropsten.etherscan.io/address/0x6f3a719c03b592c38e6a52c7e530faba2514b07c#readContract

UpgradeMaster is set and now im trying to set the upgradeagent, however when trying to do so it fails with the standard Gas estimation error. 

Now since CanUpgrade returns true and Upgradestate returns 2 (waiting for agent) and token supplies are identical ,  i suspect the issue is because of the destination contract being set not being an UpgradeAgent.

As  UpgradeAgent here needs to point to the contract address of a deployed instance of UpgradeAgent.sol . 

However when trying to publish the UpgradeAgent.sol contracteither as itself or as part of another token contract (via import) i always get the error "This contract does not implement all functions and thus cannot be created"

So how did someone who tested their upgrade feature was able to get this working because i suspect there is an issue here with the UpgradeAgent solidity file and this doesnt work the way it is out of the box and might need some mods.

Thanks for your help

**Comment by villesundell** [comment]
Sorry, I am not completely following, but have you checked https://github.com/TokenMarketNet/ico/blob/master/ico/tests/contracts/test_upgrade.py ? It outlines the process in a form of python test script.

Hopefully this helps :)

**Comment by troowala** [comment]
the dependency of the script is an instance of upgradeagent.sol deployed , which is where the issue is as this contract itself doesnt deploy the way it is now.

When trying to deploy it , it gives the error "This contract does not implement all functions and thus cannot be created." 

The issue is with this line of the code.
function upgradeFrom(address _from, uint256 _value) public;

the only way it will deploy is with this modification
function upgradeFrom(address _from, uint256 _value) public {
}

and even then it will not do anything when upgradeFrom function is called. 

So i would like to request a working example screenshot of the test_upgrade.py with necessary input parameters as currently when i run this script it simply exits with no ouput. Im using docker container provided by tokenmarket ico so all dependencies , etc are installed and other scripts such as deploy , etc work fine.

root@d984d1e5b661:/usr/src/app/ico/tests/contracts# python3 test_upgrade.py
root@d984d1e5b661:/usr/src/app/ico/tests/contracts#

Lastly i see that here
https://github.com/TokenMarketNet/ico/tree/master/ico/tests
it states next to the utils.py : upgrade agent work in progress 

So is that the case and is this peice i.e. the upgradeagent / upgradetoken functionality currently not working and is in work in progress ?

Thanks for your help

**Comment by troowala** [comment]
Hello,
Any comment on the above from your team ?

Thanks

**Comment by villesundell** [comment]
Sorry for the delayed reply!
UpgradeAgent is meant to be inherited form, as you can see in contracts/test/TestMigrationTarget.sol which can be considered as an example use of UpgradeAgent.

Contract inheriting UpgradeAgent can be the new token contract, or just a middle man contract doing the heavy lifting.
